import { type TerminalMarketDataProvider } from "./terminalApi";
import type { NormalizedTick } from "./brokerAdapter";
export interface TickData {
    type: "ticker" | "quote" | "prevClose" | "oi" | "full" | "status";
    securityId: number;
    symbol: string;
    exchangeSegment: string;
    ltp?: number;
    change?: number;
    changePercent?: number;
    open?: number;
    high?: number;
    low?: number;
    close?: number;
    prevClose?: number;
    volume?: number;
    oi?: number;
    timestamp?: number;
    source?: "terminal-os" | "proxy-websocket" | "dhan" | "zerodha";
    connected?: boolean;
    instrumentCount?: number;
    provider?: "dhan" | "zerodha";
    instrumentToken?: number;
    state?: ConnectionState | "UNAVAILABLE";
    reason?: string;
}
export type TickListener = (data: TickData) => void;
export type StatusListener = (connected: boolean) => void;
export type NormalizedTickListener = (tick: NormalizedTick) => void;
export type ConnectionState = "CONNECTED" | "CONNECTING" | "DISCONNECTED" | "RECONNECTING" | "DEGRADED" | "STALE";
export type ConnectionStateListener = (state: ConnectionState) => void;
export interface RealtimeScope {
    accountId: string;
    provider: TerminalMarketDataProvider;
    environment?: "production" | "paper" | "sandbox";
}
declare const SYMBOL_TO_SECURITY_ID: Record<string, number>;
declare const SECURITY_ID_TO_SYMBOL: Record<number, string>;
export { SYMBOL_TO_SECURITY_ID, SECURITY_ID_TO_SYMBOL };
export declare function resolveRealtimeWebSocketUrl(url?: string): string | undefined;
declare class TerminalRealtimeClient {
    private ws;
    private scope;
    private readonly tickListeners;
    private readonly globalListeners;
    private readonly statusListeners;
    private readonly connectionStateListeners;
    private readonly latestData;
    private reconnectTimer;
    private heartbeatTimer;
    private reconnectAttempt;
    private generation;
    private intentionalClose;
    private authenticated;
    private lastHeartbeatAt;
    private connectionState;
    get isConnected(): boolean;
    get isDhanConnected(): boolean;
    get isKiteConnected(): boolean;
    get state(): ConnectionState;
    get heartbeatTimestamp(): number;
    get hasReconnectTimer(): boolean;
    getLatest(securityId: number): TickData | undefined;
    getLatestBySymbol(symbol: string): TickData | undefined;
    getAllLatest(): Map<number, TickData>;
    start(scope?: RealtimeScope): void;
    connect(_provider?: "dhan" | "zerodha"): void;
    private openAuthenticatedSocket;
    private handleMessage;
    private startHeartbeatMonitor;
    private clearHeartbeatMonitor;
    private instrumentFor;
    private sendSubscription;
    subscribe(securityId: number, callback: TickListener): () => void;
    subscribeSymbol(symbol: string, callback: NormalizedTickListener): () => void;
    subscribeAll(callback: TickListener): () => void;
    onStatus(callback: StatusListener): () => void;
    onConnectionState(callback: ConnectionStateListener): () => void;
    disconnect(clearScope?: boolean): void;
    stop(): void;
    private scheduleReconnect;
    private setConnectionState;
    private notifyStatus;
}
export declare const marketWS: TerminalRealtimeClient;
