import { describe, expect, it } from "vitest";
import { PositionEngine } from "@/lib/positionEngine";

const now = new Date("2026-09-22T10:00:00.000Z");
const engine = () => new PositionEngine("account-1", { now: () => now, staleAfterMs: 60_000 });
const fill = (id: string, symbol: string, side: "BUY" | "SELL", quantity: number, price: number, instrumentKey = symbol, fees = 0) => ({ id, accountId: "account-1", symbol, instrumentKey, side, quantity, price, fees, executedAt: now.toISOString() });

describe("Phase 4 position and P&L engine", () => {
  it.each([["BUY", "LONG"], ["SELL", "SHORT"]] as const)("opens %s as %s", (side, expected) => expect(engine().applyExecution(fill("1", "NIFTY", side, 10, 100))?.side).toBe(expected));
  it("adds same-direction fills using a weighted average", () => { const value = engine(); value.applyExecution(fill("1", "NIFTY", "BUY", 10, 100)); expect(value.applyExecution(fill("2", "NIFTY", "BUY", 5, 130))).toMatchObject({ quantity: 15, averageEntryPrice: 110 }); });
  it("partially closes both directions without changing average", () => { const value = engine(); value.applyExecution(fill("1", "NIFTY", "BUY", 10, 100)); expect(value.applyExecution(fill("2", "NIFTY", "SELL", 4, 125))).toMatchObject({ quantity: 6, averageEntryPrice: 100, realizedPnl: 100 }); const short = engine(); short.applyExecution(fill("1", "BANKNIFTY", "SELL", 10, 200)); expect(short.applyExecution(fill("2", "BANKNIFTY", "BUY", 4, 175))).toMatchObject({ quantity: 6, realizedPnl: 100 }); });
  it("closes and reverses positions", () => { const value = engine(); value.applyExecution(fill("1", "NIFTY", "BUY", 10, 100)); expect(value.applyExecution(fill("2", "NIFTY", "SELL", 15, 90))).toMatchObject({ side: "SHORT", quantity: 5, averageEntryPrice: 90, realizedPnl: -100 }); const short = engine(); short.applyExecution(fill("1", "BANKNIFTY", "SELL", 10, 200)); expect(short.applyExecution(fill("2", "BANKNIFTY", "BUY", 15, 180))).toMatchObject({ side: "LONG", quantity: 5, realizedPnl: 200 }); });
  it("removes a zero quantity position and calculates realized/unrealized P&L", () => { const value = engine(); value.applyExecution(fill("1", "INFY", "BUY", 2, 100)); value.valueMarketPrice({ symbol: "INFY", price: 125, asOf: now.toISOString() }); expect(value.accountValuation(1_000)).toMatchObject({ realizedPnl: 0, unrealizedPnl: 50, equity: 1_050 }); value.applyExecution(fill("2", "INFY", "SELL", 2, 120)); expect(value.getPositions()).toHaveLength(0); expect(value.accountValuation(1_000).realizedPnl).toBe(40); });
  it("isolates instruments, applies fees, rejects invalid and duplicate executions", () => { const value = engine(); value.applyExecution(fill("1", "NIFTY", "BUY", 1, 100, "NIFTY", 2)); value.applyExecution(fill("2", "BANKNIFTY", "SELL", 1, 200)); expect(value.getPositions()).toHaveLength(2); expect(() => value.applyExecution(fill("3", "NIFTY", "BUY", 0, 100))).toThrow(); expect(() => value.applyExecution(fill("4", "NIFTY", "BUY", 1, 0))).toThrow(); expect(value.applyExecution(fill("1", "NIFTY", "BUY", 1, 100))?.quantity).toBe(1); });
  it("reports stale and unavailable data without fabricating a price", () => { const value = engine(); value.applyExecution(fill("1", "NIFTY", "BUY", 1, 100)); expect(value.valueMarketPrice({ symbol: "NIFTY", price: 110, asOf: "2026-09-22T09:00:00.000Z" })?.valuationStatus).toBe("STALE"); expect(value.valueMarketPrice({ symbol: "NIFTY", price: null })?.valuationStatus).toBe("UNAVAILABLE"); expect(value.accountValuation(1_000).equity).toBeNull(); });
  it("rejects wrong-account executions and exposes a risk snapshot", () => { const value = engine(); expect(() => value.applyExecution({ ...fill("1", "NIFTY", "BUY", 1, 100), accountId: "account-2" })).toThrow(); value.applyExecution(fill("1", "NIFTY", "BUY", 2, 100)); value.valueMarketPrice({ symbol: "NIFTY", price: 110 }); expect(value.riskSnapshot()[0]).toMatchObject({ quantity: 2, side: "LONG", exposure: 220, unrealizedPnl: 20 }); });
});